# Generated by Django 5.1.7 on 2025-03-13 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airesponse',
            old_name='Conversation',
            new_name='conversation',
        ),
    ]
