# Generated by Django 5.1.7 on 2025-03-14 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_rename_timestamp_airesponse_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airesponse',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='airesponse',
            name='message_text',
        ),
        migrations.RemoveField(
            model_name='airesponse',
            name='user',
        ),
        migrations.AddField(
            model_name='airesponse',
            name='message',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='ai_response', to='chat.message'),
            preserve_default=False,
        ),
    ]
