# Generated by Django 5.1.7 on 2025-03-19 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_airesponse_conversation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airesponse',
            name='message',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='conversation_type',
        ),
        migrations.AddField(
            model_name='airesponse',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_responses', to='chat.conversation'),
        ),
        migrations.AddField(
            model_name='airesponse',
            name='message_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='chatuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='name',
            field=models.CharField(default='Support Chat', max_length=255),
        ),
        migrations.AddField(
            model_name='websocketsession',
            name='last_active',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
