# Generated by Django 5.1.7 on 2025-03-20 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_conversation_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConversationParticipant',
        ),
    ]
